### ISSUE TITLE
Error in: if(shades::lightness(text$fill) < 50) on line 297 in geom_fit_text.R

### ISSUE THREAD

**Issue by sda030** [wilkox/ggfittext#20] opened 2020-03-21 18:39 UTC
A few places you have correctly corrected the reverse-colours feature to account for no fill-colour. However, on line 297 in geom_fit_text.R there seems to be missing this "correction". At least I get an `Error in if (shades::lightness(text$fill) < 50) { : missing value where TRUE/FALSE needed` if I have missing among the fill values.

Otherwise a great package!

**Comment by wilkox** [comment] 2020-04-25 06:54
Thanks for the bug report @sda030! I'm having trouble reproducing this bug though. For example, the following seems to work without an error:

``` r
library(ggplot2)
library(ggfittext)

animals$mass[3] <- NA

ggplot(animals, aes(x = type, y = flies, fill = mass, label = animal)) +
  geom_tile() +
  geom_fit_text(reflow = TRUE, grow = TRUE, contrast = TRUE, size = 48)
```

![](https://i.imgur.com/fdn39qH.png)

<sup>Created on 2020-04-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Could you please provide a [reprex](https://reprex.tidyverse.org) of your code that produces this error? Thanks!

**Comment by davised** [comment] 2020-12-09 10:16
I ran into this problem as well. Here you can reproduce it:

``` r
library(ggplot2)
library(ggfittext)
animals$type <- factor(c('feathers', 'feathers', 'fur', 'fur', NA, NA))
n_type <- nlevels(animals$type)

ggplot(animals, aes(x = animal, y = mass, color = type, 
                    fill = type, label = mass)) +
  geom_bar(stat='identity') +
  geom_bar_text(contrast = TRUE) +
  scale_color_manual(values = colorRampPalette(c('firebrick','lightblue'))(n_type),
                     aesthetics = c('fill', 'color')) +
  theme_bw()
#> Error in if (abs(shades::lightness(bg_colour) - shades::lightness(text_colour)) < : missing value where TRUE/FALSE needed
```

![](https://i.imgur.com/zCgRkKX.png)

<sup>Created on 2020-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This issue can be resolved by:

```r
scale_color_manual(..., na.value='#000000')
```
(or whatever value you want to use for NA)

I'm guessing the original user had an NA in their data and did not provide enough values and/or did not set the na.value option.

**Comment by davised** [comment] 2020-12-09 10:27
Here's another example without the colorRampPalette, and just setting one value to NA.

You'll notice without a scale_color_manual, there is a problem where the background color isn't detected properly as well, but not a complete error. I supplied enough colors to cover the NA instance, but those are ignored.

``` r
library(ggplot2)
library(ggfittext)
animals$type[6] <- NA

ggplot(animals, aes(x = animal, y = mass, color = type, 
                    fill = type, label = mass)) +
  geom_bar(stat='identity') +
  geom_bar_text(contrast = TRUE) +
  theme_bw()
```

![](https://i.imgur.com/btewyX4.png)

``` r
ggplot(animals, aes(x = animal, y = mass, color = type, 
                    fill = type, label = mass)) +
  geom_bar(stat='identity') +
  geom_bar_text(contrast = TRUE) +
  scale_color_manual(values = c('firebrick', 'lightblue', 'goldenrod', 'gray'),
                     aesthetics = c('fill', 'color'),
                     na.value='#000000') +
  theme_bw()
```

![](https://i.imgur.com/bziuw3U.png)

``` r
ggplot(animals, aes(x = animal, y = mass, color = type, 
                    fill = type, label = mass)) +
  geom_bar(stat='identity') +
  geom_bar_text(contrast = TRUE) +
  scale_color_manual(values = c('firebrick', 'lightblue', 'goldenrod', 'gray'),
                     aesthetics = c('fill', 'color')) +
  theme_bw()
#> Error in if (abs(shades::lightness(bg_colour) - shades::lightness(text_colour)) < : missing value where TRUE/FALSE needed
```

![](https://i.imgur.com/pT2xcwn.png)

<sup>Created on 2020-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wilkox** [comment] 2021-01-03 03:44
@davised Thanks for providing the examples but unfortunately I still can't reproduce this bug with the current release version of `ggfittext`:

``` r
library(ggfittext)
library(ggplot2)
packageVersion("ggfittext")
#> [1] '0.9.0'

ggplot(animals, aes(x = animal, y = mass, color = type, 
                    fill = type, label = mass)) +
  geom_bar(stat='identity') +
  geom_bar_text(contrast = TRUE) +
  scale_color_manual(values = c('firebrick', 'lightblue', 'goldenrod', 'gray'),
                     aesthetics = c('fill', 'color')) +
  theme_bw()
```

![](https://i.imgur.com/7tiLgnv.png)

<sup>Created on 2021-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I wonder if this is an issue with the shades package? Would you mind letting me know what version of shades you have installed (`packageVersion("shades")`)?

**Comment by davised** [comment] 2021-01-03 03:49
I'll check when I get to my PC. Did you set a value to NA? Eg

animals​$​type​[​6​] ​<-​ ​NA​

**Comment by wilkox** [comment] 2021-01-03 04:09
I might be misunderstanding the problem, but it seems to me that even with an NA in 'type' the issue is not with ggfittext but with `scale_colour_manual()` failing to map a colour for the NA value. This can be fixed with the `na.value` argument e.g.:

``` r
library(ggfittext)
library(ggplot2)
packageVersion("ggfittext")
#> [1] '0.9.0'

animals$type[6] <- NA

ggplot(animals, aes(x = animal, y = mass, fill = type, colour = type, label = mass)) +
  geom_bar(stat='identity') +
  geom_bar_text(contrast = TRUE) +
  scale_colour_manual(
    aesthetics = c("colour", "fill"),
    values = c('firebrick', 'lightblue', 'goldenrod'),
    na.value = 'lightgray'
  ) +
  theme_bw()
```

![](https://i.imgur.com/sLX8ZqB.png)

<sup>Created on 2021-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davised** [comment] 2021-01-03 04:16
Yes the na.value option can resolve the issue, but the ggfittext call is throwing the error in the example. 

Users will likely come here for help again in the future because of this. 

Furthermore, as I mentioned, the contrast doesn't work properly if the na.value isn't supplied.

**Comment by wilkox** [comment] 2021-01-03 09:22
I think you're right that users will be confused by this error. I've made a change so that this situation will result in a warning rather than stopping with an error. I'll be submitting this version to CRAN within the next few days.

``` r
library(ggfittext)
library(ggplot2)
packageVersion("ggfittext")
#> [1] '0.9.1'

animals$type[6] <- NA

ggplot(animals, aes(x = animal, y = mass, color = type, 
                    fill = type, label = mass)) +
  geom_bar(stat='identity') +
  geom_bar_text(contrast = TRUE) +
  scale_color_manual(values = c('firebrick', 'lightblue', 'goldenrod', 'gray'),
                     aesthetics = c('fill', 'color')) +
  theme_bw()
#> Warning: For label '5000', trying to contrast text against a fill of 'NA'
```

![](https://i.imgur.com/qTNzkFP.png)

<sup>Created on 2021-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed as completed** 2021-01-03 09:23 UTC
